export const FOOTER_HEIGHT = 30
export const HEADER_HEIGHT = 60
export const DRAWER_WIDTH = 250

// APP TEXT
export const APP_TITLE =
  'Makhzan, Best website to find your most suitable storage unit or renting it'
export const FOOTER_TEXT = `${new Date().getFullYear()} Proudly developed by Mohamed Salem`

export const GOVERNORATES = [
  'Alexandria',
  'Aswan',
  'Asyut',
  'Beheira',
  'Beni Suef',
  'Cairo',
  'Dakahlia',
  'Damietta',
  'Faiyum',
  'Gharbia',
  'Giza',
  'Ismailia',
  'Kafr El Sheikh',
  'Luxor',
  'Matruh',
  'Minya',
  'Monufia',
  'New Valley',
  'North Sinai',
  'Port Said',
  'Qalyubia',
  'Qena',
  'Red Sea',
  'Sharqia',
  'Sohag',
  'South Sinai',
  'Suez',
]

export const LOCATIONS = [
  '6 October',
  'Agouza',
  'Ain Shams',
  'Arish',
  'Aswan',
  'Asyut',
  'Abbassia',
  'Bab El Sharia',
  'Banha',
  'Beni Suef',
  'Borg El Arab',
  'Bulaq',
  'Bulaq El Dakrur',
  'Coptic Cairo',
  'Dahab',
  'Daher',
  'Downtown',
  'Damanhur',
  'Dar El Salam',
  'Dekhela',
  'Dokki',
  'El Ahram',
  'El Badari',
  'El Badrashein',
  'El Basatin',
  'El Dabaa',
  'El Darb El Ahmar',
  'El Gomrok',
  'El Mahalla El Kubra',
  'El Mahmoudia',
  'El Manasra',
  'El Mansheya',
  'El Marg	',
  'El Matareya',
  'El Nozha',
  'El Omraniya',
  'El Salam',
  'El Sayeda Zeinab',
  'El Sharabiya',
  'El Sharq',
  'El Shorouk',
  'El Manial',
  'El Qobbah',
  'El Rehab',
  'Faisal',
  'Faiyum',
  'Fustat',
  'Gamasa',
  'Giza',
  'Garden City',
  'Hadaiq El Qobbah',
  'Halaib',
  'Heliopolis',
  'Helwan',
  'Hurghada',
  'Imbaba',
  'Ismailia',
  'Kafr El Dawwar',
  'Kafr El Sheikh',
  'Kafr Saad',
  'Kafr Saqr',
  'Karmoz',
  'Luxor',
  'Maadi',
  'Mansoura',
  'Marina El Alamein',
  'Marsa Alam',
  'Menouf',
  'Mersa Matruh',
  'Minya',
  'Minya El Qamh',
  'Mit Ghamr',
  'Moharam Bek',
  'Monshat El Nasr',
  'Nag Hammadi',
  'Nasir Bush',
  'Nasr City',
  'New Akhmim',
  'New Aswan',
  'New Asyut',
  'New Beni Suef',
  'New Borg El Arab',
  'New Cairo',
  'New Damietta',
  'New Faiyum',
  'New Minya',
  'New Qena',
  'New Salhia',
  'New Sohag',
  'New Toshka',
  'North Coast',
  'Obour',
  'Old Cairo',
  'Port Fuad',
  'Sadat City',
  'Safaga',
  'Sahil Salim',
  'Saint Catherine',
  'Sallum',
  'Sharm El Sheikh',
  'Sheikh Zayed',
  'Sheikh Zuweid',
  'Shibin El Kom',
  'Shibin El Qanatir',
  'Shubra',
  'Shubra El Kheima',
  'Siwa',
  'Sohag',
  'Suez',
  'Taba',
  'Tanta',
  'Tura',
  'Zagazig',
  'Zamalek',
  'Zeitoun',
]

