export const FOOTER_HEIGHT = 30
export const HEADER_HEIGHT = 60
export const DRAWER_WIDTH = 250

// APP TEXT
export const APP_TITLE =
  'Makhzan, Best website to find your most suitable storage unit or renting it'
export const FOOTER_TEXT = `${new Date().getFullYear()} Proudly developed by Mohamed Salem`

export const GOVERNORATES = [
  'Alexandria',
  'Aswan',
  'Asyut',
  'Beheira',
  'Beni Suef',
  'Cairo',
  'Dakahlia',
  'Damietta',
  'Faiyum',
  'Gharbia',
  'Giza',
  'Ismailia',
  'Kafr El Sheikh',
  'Luxor',
  'Matruh',
  'Minya',
  'Monufia',
  'New Valley',
  'North Sinai',
  'Port Said',
  'Qalyubia',
  'Qena',
  'Red Sea',
  'Sharqia',
  'Sohag',
  'South Sinai',
  'Suez',
]

export const LOCATIONS = [
  '6 October',
  '10th of Ramadan',
  '15 May',
  'Abdeen',
  'Abnub',
  'Abu El Matamir',
  'Abu Hammad',
  'Abu Hummus',
  'Abu Kebir',
  'Abu Radis',
  'Abu Simbel',
  'Abu Tig',
  'Abu Tisht',
  'Abu Zenima',
  'Aga',
  'Agouza',
  'Ain Shams',
  'Akhmim',
  'Amreya',
  'Arish',
  'Armant',
  'Ashmoun',
  'Aswan',
  'Asyut',
  'Ataka',
  'Atfih',
  'Awlad Saqr',
  'Awsim',
  'Azbakeya',
  'Bab El Sharia',
  'Bab Sharq',
  'Badr',
  'Banha',
  'Baris Shurta',
  'Basyoun',
  'Beni Ebeid',
  'Beni Mazar',
  'Beni Suef',
  'Biba',
  'Bilbeis',
  'Bilqas',
  'Bir El Abd',
  'Birket El Sab',
  'Biyala',
  'Borg El Arab',
  'Bulaq',
  'Bulaq El Dakrur',
  'Burullus',
  'Dahab',
  'Dairut',
  'Damanhur',
  'Damietta',
  'Dar El Salam',
  'Deir Mawas',
  'Dekernes',
  'Dekhela',
  'Desouk',
  'Dishna',
  'Diyarb Negm',
  'Dokki',
  'Edfu',
  'El Ahram',
  'El Arab',
  'El Arbein',
  'El Ayyat',
  'El Badari',
  'El Badrashein',
  'El Bagour',
  'El Balyana',
  'El Basal Port',
  'El Basatin',
  'El Dabaa',
  'El Darb El Ahmar',
  'El Dawahy',
  'El Delengat',
  'El Fashn',
  'El Fath',
  'El Gamaliya',
  'El Ganayin',
  'El Ghanayem',
  'El Gomrok',
  'El Hamam',
  'El Hamool',
  'El Hassana',
  'El Hawamdiya',
  'El Husseiniya',
  'El Ibrahimiya',
  'El Idwa',
  'El Kawsar',
  'El Khalifa',
  'El Labban',
  'El Mahalla El Kubra',
  'El Mahmoudia',
  'El Manakh',
  'El Manasra',
  'El Mansheya',
  'El Manzala',
  'El Maragha',
  'El Marg	',
  'El Matareya',
  'El Muski',
  'El Nozha',
  'El Omraniya',
  'El Qanater El Khayreya',
  'El Qanayat',
  'El Qantara',
  'El Qantara El Sharqiya',
  'El Rahmaniya',
  'El Raml',
  'El Reyad',
  'El Saff',
  'El Salam',
  'El Santa',
  'El Sayeda Zeinab',
  'El Segil',
  'El Senbellawein',
  'El Sharabiya',
  'El Sharq',
  'El Shohada',
  'El Shorouk',
  'El Tebbin',
  'El Tor',
  'El Usayrat',
  'El Wahat El Bahariya',
  'El Wahat El Khariga',
  'El Waqf',
  'El Warraq',
  'El Wasta',
  'El Weili',
  'El Zaher',
  'El Zarqa',
  'El Zawya El Hamra',
  'El Zohur',
  'Esna',
  'Faisal',
  'Faiyum',
  'Faqous',
  'Faraskur',
  'Farshut',
  'Fayed',
  'Fuwa',
  'Gamasa',
  'Ganoubi',
  'Gharb Nubariya',
  'Girga',
  'Giza',
  'Hadaiq El Qobbah',
  'Halaib ',
  'Heliopolis',
  'Helwan',
  'Hihya',
  'Hosh Essa',
  'Hurghada',
  'Ibsheway',
  'Ihnasiya',
  'Imbaba',
  'Ismailia',
  'Itay El Barud',
  'Itsa',
  'Juhayna El Gharbiyah',
  'Kafr El Dawwar',
  'Kafr El Sheikh',
  'Kafr El Zayat',
  'Kafr Saad',
  'Kafr Saqr',
  'Kafr Shukr',
  'Karmoz',
  'Kerdasa',
  'Khanka',
  'Khusus',
  'Kom Hamada',
  'Kom Ombo',
  'Kotoor',
  'Luxor',
  'Maadi',
  'Maghaghah',
  'Mahallat Dimna',
  'Mallawi',
  'Manfalut',
  'Mansoura',
  'Marina El Alamein',
  'Marsa Alam',
  'Mashtool El Souk',
  'Matay',
  'Menouf',
  'Mersa Matruh',
  'Metoubes',
  'Minya',
  'Minya El Qamh',
  'Minyet El Nasr',
  'Mit Ghamr',
  'Mit Salsil',
  'Moharam Bek',
  'Monshat El Nasr',
  'Montaza',
  'Mubarak Sharq El Tafrea',
  'Nabaroh',
  'Nag Hammadi',
  'Nakhl',
  'Naqada',
  'Nasir Bush',
  'Nasr',
  'Nasr City',
  'New Akhmim',
  'New Aswan',
  'New Asyut',
  'New Beni Suef',
  'New Borg El Arab',
  'New Cairo',
  'New Damietta',
  'New Faiyum',
  'New Minya',
  'New Qena',
  'New Salhia',
  'New Sohag',
  'New Toshka',
  'North Coast',
  'Nuweiba',
  'Obour',
  'Old Cairo',
  'Port Fuad',
  'Qaha',
  'Qallin',
  'Qalyub',
  'Qasr El Nil',
  'Qena',
  'Qift',
  'Quesna',
  'Qus',
  'Rafah',
  'Ras El Bar',
  'Ras Gharib',
  'Ras Sidr',
  'Rod El Farag',
  'Rosetta',
  'Sadat City',
  'Safaga',
  'Sahil Salim',
  'Saint Catherine',
  'Sallum',
  'Samalut',
  'Samanoud',
  'Saqultah',
  'Sers El Lyan',
  'Shalateen',
  'Sharm El Sheikh',
  'Sheikh Zayed',
  'Sheikh Zuweid',
  'Shibin El Kom',
  'Shibin El Qanatir',
  'Shirbin',
  'Shubra',
  'Shubra El Kheima',
  'Shubrakhit',
  'Sidfa',
  'Sidi Barrani',
  'Sidi Gaber',
  'Sidi Salem',
  'Sinnuris',
  'Siwa',
  'Sohag',
  'Suez',
  'Suez Port Police Dept',
  'Sumusta El Waqf',
  'Taba',
  'Tahta',
  'Tala',
  'Talkha',
  'Tamiya',
  'Tanta',
  'Tell El Kebir',
  'Tibah Police Dept',
  'Timay El Imdid',
  'Tukh',
  'Tura',
  'Wadi El Natrun',
  'Yousef El Seddik',
  'Zagazig',
  'Zamalek',
  'Zefta',
  'Zeitoun',
]
